### ISSUE TITLE
No module named 'bmpy_utils'

### ISSUE THREAD

**Issue by Benature** [p4pktgen/p4pktgen#133]
Hi, I ran the first demo as https://github.com/p4pktgen/p4pktgen/blob/master/docs/p4pktgen-intro-by-example.md#first-run-wth-program-demo1p4_16p4, but the `log1.txt` shows an error. What should I do?

the command is 
```shell
p4pktgen examples/demo1.p4_16.json >& log1.txt
```

the file content is 
```txt
Traceback (most recent call last):
  File "/home/user/p4/p4pktgen/my-venv/bin/p4pktgen", line 33, in <module>
    sys.exit(load_entry_point('p4pktgen', 'console_scripts', 'p4pktgen')())
  File "/home/user/p4/p4pktgen/my-venv/bin/p4pktgen", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/user/p4/p4pktgen/my-venv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/home/user/p4/p4pktgen/my-venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/p4/p4pktgen/src/p4pktgen/main.py", line 7, in <module>
    from p4pktgen.core.strategy import ParserGraphVisitor
  File "/home/user/p4/p4pktgen/src/p4pktgen/core/strategy.py", line 6, in <module>
    from p4pktgen.core.path import Path, PathModel
  File "/home/user/p4/p4pktgen/src/p4pktgen/core/path.py", line 4, in <module>
    from p4pktgen.core.test_cases import TestPathResult
  File "/home/user/p4/p4pktgen/src/p4pktgen/core/test_cases.py", line 8, in <module>
    from p4pktgen.switch.simple_switch import SimpleSwitch
  File "/home/user/p4/p4pktgen/src/p4pktgen/switch/simple_switch.py", line 12, in <module>
    from p4pktgen.switch.runtime_CLI import RuntimeAPI, PreType, thrift_connect, load_json_config
  File "/home/user/p4/p4pktgen/src/p4pktgen/switch/runtime_CLI.py", line 40, in <module>
    import bmpy_utils as utils
ModuleNotFoundError: No module named 'bmpy_utils'
```

**Comment by iand-xilinx** [comment]
`bmpy_utils` is part of [p4lang/behavioral-model](https://github.com/p4lang/behavioral-model/), which also includes `simple_switch`. The setup instructions at [docs/install.md](https://github.com/p4pktgen/p4pktgen/blob/master/docs/install.md) document the dependencies, and point to a script that will install `behavioral-model`.  Alternatively, you can refer to [`.travis.yml`](https://github.com/p4pktgen/p4pktgen/blob/master/.travis.yml) for the setup that we use in CI.
