### ISSUE TITLE
BugReport: p4pktgen crashes when p4 code compares a boolean variable against a boolean literal

### ISSUE THREAD

**Issue by JehandadKhan** [p4pktgen/p4pktgen#81]
The offending snippet of code is 
```
if ((meta.sip.sip_match== false) && (meta.sip.is_north_lnk == false))
  drop();
}

```
a workaround is to re-write the above code as 
```
if (!(meta.sip.sip_match) && !(meta.sip.is_north_lnk))
  drop();
}
```
Note: This might be a p4c/JSON quirk 

Traceback (most recent call last):
  File "/usr/local/bin/p4pktgen", line 11, in <module>
    load_entry_point('p4pktgen', 'console_scripts', 'p4pktgen')()
  File "/root/p4pktgen/src/p4pktgen/main.py", line 166, in main
    generate_graphs=args.generate_graphs)
  File "/root/p4pktgen/src/p4pktgen/main.py", line 475, in process_json_file
    neighbor_order_callback=order_cb_fn)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 87, in generate_all_paths
    generate_all_paths_(v_start)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 80, in generate_all_paths_
    generate_all_paths_(neighbor)
  File "/root/p4pktgen/src/p4pktgen/util/graph.py", line 74, in generate_all_paths_
    go_deeper = callback(copy.copy(path_so_far), False)
  File "/root/p4pktgen/src/p4pktgen/main.py", line 375, in eval_control_path
    source_info_to_node_name, count, is_complete_control_path)
  File "/root/p4pktgen/src/p4pktgen/core/translator.py", line 694, in generate_constraints
    conditional.expression)
  File "/root/p4pktgen/src/p4pktgen/core/translator.py", line 162, in type_value_to_smt
    sym_packet, pos)
  File "/root/p4pktgen/src/p4pktgen/core/translator.py", line 191, in type_value_to_smt
    lhs, rhs = self.equalize_bv_size([lhs, rhs])
  File "/root/p4pktgen/src/p4pktgen/core/translator.py", line 121, in equalize_bv_size
    target_size = max([bv.size() for bv in bvs])
AttributeError: BoolRef instance has no attribute 'size'

**Comment by 4tXJ7f** [comment]
I am not able to reproduce this issue with the newest version of master.
